### ISSUE TITLE
Problem with crashing on free and accessing unallocated memory

### ISSUE THREAD

**Issue by skjaro** [grke/burp#845]
Hi,

There is a problem with burp server code it is in all versions of 2 version. I am sending report from 2.3.20 version of code. There is problem with monitor mode in burp it is crashing on server side constanly in my enviroment.
This is report of backtrace:
```
#0  0x00007ffff63b6207 in raise () from /lib64/libc.so.6
#1  0x00007ffff63b78f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff63f8d27 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff6401489 in _int_free () from /lib64/libc.so.6
#4  0x0000000000407126 in free_v (ptr=0x863108, ptr@entry=0x863110) at src/alloc.c:106
#5  free_w (str=str@entry=0x863108) at src/alloc.c:115
#6  0x0000000000417322 in iobuf_free_content (iobuf=iobuf@entry=0x863100) at src/iobuf.c:33
#7  0x000000000041a2a2 in sbuf_free_content (sb=sb@entry=0x8630d0) at src/sbuf.c:39
#8  0x000000000043e038 in do_browse_manifest (browse=0x7c28c0 "", sb=0x8630d0, manio=0x862f70) at src/server/monitor/browse.c:28
#9  browse_manifest_start (browse=browse@entry=0x7c28c0 "", use_cache=use_cache@entry=0, bu=0x862430, bu=0x862430, cstat=0x703a70, cstat=0x703a70) at src/server/monitor/browse.c:78
#10 0x000000000043e225 in browse_manifest (cstat=cstat@entry=0x703a70, bu=bu@entry=0x862430, browse=browse@entry=0x7c28c0 "", use_cache=<optimized out>, use_cache@entry=0) at src/server/monitor/browse.c:102
#11 0x000000000043fd9e in json_send_backup (cstat=cstat@entry=0x703a70, bu=bu@entry=0x862430, logfile=logfile@entry=0x7c5c00 "manifest", browse=browse@entry=0x7c28c0 "", use_cache=use_cache@entry=0,
    peer_version=peer_version@entry=20320, print_flags=1) at src/server/monitor/json_output.c:290
#12 0x000000000044005c in json_send_client_backup (cstat=cstat@entry=0x703a70, bu1=bu1@entry=0x862430, bu2=bu2@entry=0x0, logfile=logfile@entry=0x7c5c00 "manifest", browse=browse@entry=0x7c28c0 "", use_cache=use_cache@entry=0,
    peer_version=peer_version@entry=20320) at src/server/monitor/json_output.c:389
#13 0x000000000044023b in json_send (asfd=asfd@entry=0x6c03f0, clist=clist@entry=0x716920, cstat=0x703a70, bu=0x862430, logfile=0x7c5c00 "manifest", browse=0x7c28c0 "", use_cache=use_cache@entry=0, peer_version=20320)
    at src/server/monitor/json_output.c:433
#14 0x0000000000440dce in parse_client_data (srfd=srfd@entry=0x6c03f0, clist=0x716920, monitor_browse_cache=monitor_browse_cache@entry=0, peer_version=peer_version@entry=0x7fffffffdf20) at src/server/monitor/status_server.c:389
#15 0x000000000044111b in parse_data (peer_version=0x7fffffffdf20, monitor_browse_cache=0, cfd=0x6c03f0, clist=<optimized out>, asfd=0x6c03f0) at src/server/monitor/status_server.c:412
#16 status_server (as=as@entry=0x6ba750, monitor_cconfs=monitor_cconfs@entry=0x6a6060) at src/server/monitor/status_server.c:530
#17 0x0000000000431b7b in child (as=0x6ba750, is_status_server=1, status_wfd=-1, status_wfd@entry=11, confs=<optimized out>, cconfs=0x6a6060) at src/server/child.c:211
#18 0x0000000000434fb3 in run_child (cfd=cfd@entry=0x7fffffffe0c8, ctx=ctx@entry=0x69f830, addr=addr@entry=0x7fffffffe0f0, status_wfd=11, status_rfd=-1, conffile=conffile@entry=0x7fffffffe765 "/etc/burp/burp-server.conf",
    forking=forking@entry=1, peer_addr=peer_addr@entry=0x7fffffffe210 "127.0.0.1") at src/server/main.c:323
#19 0x0000000000435679 in process_incoming_client (asfd=0x6a3490, ctx=ctx@entry=0x69f830, conffile=conffile@entry=0x7fffffffe765 "/etc/burp/burp-server.conf", confs=confs@entry=0x67f030) at src/server/main.c:538
#20 0x0000000000435bbc in run_server (conffile=0x7fffffffe765 "/etc/burp/burp-server.conf", confs=0x67f030) at src/server/main.c:766
#21 server (confs=confs@entry=0x67f030, conffile=conffile@entry=0x7fffffffe765 "/etc/burp/burp-server.conf", lock=<optimized out>, generate_ca_only=generate_ca_only@entry=0) at src/server/main.c:878
#22 0x0000000000406eb6 in server_modes (confs=0x67f030, generate_ca_only=0, lock=<optimized out>, conffile=0x7fffffffe765 "/etc/burp/burp-server.conf", act=<optimized out>) at src/prog.c:224
#23 real_main (argv=<optimized out>, argc=<optimized out>) at src/prog.c:568
#24 main (argc=<optimized out>, argv=<optimized out>) at src/prog.c:588
```

With valgrind testing it does not crash and there is some error on accessing memory which is not allocated:
```
==20230== Invalid write of size 1
==20230==    at 0x409BDF: to_base64 (base64.c:92)
==20230==    by 0x4092D7: attribs_encode (attribs.c:124)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==  Address 0x9f636c5 is 1 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==
==20230== Invalid write of size 1
==20230==    at 0x409C05: to_base64 (base64.c:95)
==20230==    by 0x4092D7: attribs_encode (attribs.c:124)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==  Address 0x9f636c4 is 0 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==
==20230== Invalid write of size 1
==20230==    at 0x4092E1: attribs_encode (attribs.c:125)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==    by 0x435BBB: run_server (main.c:766)
==20230==    by 0x435BBB: server (main.c:878)
==20230==  Address 0x9f636c5 is 1 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==
==20230== Invalid write of size 1
==20230==    at 0x409BDF: to_base64 (base64.c:92)
==20230==    by 0x4092FD: attribs_encode (attribs.c:126)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==  Address 0x9f636c7 is 3 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==
==20230== Invalid write of size 1
==20230==    at 0x409C05: to_base64 (base64.c:95)
==20230==    by 0x4092FD: attribs_encode (attribs.c:126)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==  Address 0x9f636c6 is 2 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==
==20230== Invalid write of size 1
==20230==    at 0x40930A: attribs_encode (attribs.c:129)
==20230==    by 0x4344E2: check_browsedir (list.c:127)
==20230==    by 0x43E097: do_browse_manifest (browse.c:48)
==20230==    by 0x43E097: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
==20230==    by 0x434FB2: run_child (main.c:323)
==20230==    by 0x435678: process_incoming_client.constprop.4 (main.c:538)
==20230==    by 0x435BBB: run_server (main.c:766)
==20230==    by 0x435BBB: server (main.c:878)
==20230==  Address 0x9f636c7 is 3 bytes after a block of size 52 alloc'd
==20230==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==20230==    by 0x40707C: malloc_w (alloc.c:72)
==20230==    by 0x4171F1: do_iobuf_fill_from_fzp (iobuf.c:156)
==20230==    by 0x41A3EC: sbuf_fill (sbuf.c:348)
==20230==    by 0x436D7F: manio_read_with_blk (manio.c:431)
==20230==    by 0x43E042: do_browse_manifest (browse.c:29)
==20230==    by 0x43E042: browse_manifest_start.isra.0 (browse.c:78)
==20230==    by 0x43FD9D: json_send_backup.constprop.5 (json_output.c:290)
==20230==    by 0x44005B: json_send_client_backup (json_output.c:389)
==20230==    by 0x44023A: json_send (json_output.c:433)
==20230==    by 0x440DCD: parse_client_data (status_server.c:389)
==20230==    by 0x44111A: parse_data (status_server.c:412)
==20230==    by 0x44111A: status_server (status_server.c:530)
==20230==    by 0x431B7A: child (child.c:211)
```

**Comment by grke** [comment]
Hello,
Thank you for the backtraces.
Is there anything specific that you are doing with the monitor that triggers the segfault?
Or do you just start the monitor, then it segfaults without any other input from you?

**Comment by skjaro** [comment]
I am testing it manually and it crashes mostly in listing files of client backup. With command:
```
c:clinet1234:b:241:p:
```

**Comment by grke** [comment]
Thank you, I think I have tracked the problem down.
Fix coming up.

**Comment by grke** [comment]
Fix in now in master, ready for the next release.

**Comment by skjaro** [comment]
Thanks. It is resolved in my enviroment.

**Comment by grke** [comment]
Thanks for confirming.
